import { useState } from 'react';
import { Link } from 'react-router-dom';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { seedData, addNewIncident, makeResourceUnavailable, changeSeverity, resetSimulation } from '../lib/api/simulation';
import { generatePlan, replan } from '../lib/api/planning';
import { 
  FlaskConical, Plus, Database, Zap, RefreshCw, RotateCcw, 
  Ambulance, Terminal, Loader2, ArrowRight
} from 'lucide-react';
import { useIncidents } from '../hooks/useIncidents';
import { useResources } from '../hooks/useResources';
import SeverityBadge from '../components/ui/SeverityBadge';
import StatusBadge from '../components/ui/StatusBadge';
import ResourceIcon from '../components/ui/ResourceIcon';

export default function Simulation() {
  const [log, setLog] = useState<string[]>([
    `${new Date().toLocaleTimeString()} — Simulation controller ready. Execute scenario steps below.`,
  ]);
  const [activeStep, setActiveStep] = useState<number>(0);
  const qc = useQueryClient();
  const { data: incidents } = useIncidents();
  const { data: resources } = useResources();

  const addLog = (msg: string) => setLog(prev => [`${new Date().toLocaleTimeString()} — ${msg}`, ...prev]);

  const seedMut = useMutation({ 
    mutationFn: async () => {
      return new Promise((resolve) => {
        let settled = false;
        const fallback = () => {
          if (!settled) {
            settled = true;
            resolve(seedData());
          }
        };
        const timer = setTimeout(fallback, 1500);

        if (typeof navigator !== 'undefined' && navigator.geolocation) {
          navigator.geolocation.getCurrentPosition(
            pos => {
              if (!settled) {
                settled = true;
                clearTimeout(timer);
                resolve(seedData({ lat: pos.coords.latitude, lng: pos.coords.longitude }));
              }
            },
            () => fallback(),
            { timeout: 1500, maximumAge: 60000 }
          );
        } else {
          fallback();
        }
      });
    }, 
    onSuccess: () => { 
      setActiveStep(1);
      addLog('Database seeded with 3 local incidents & 17 emergency fleet assets.'); 
      qc.invalidateQueries(); 
    },
    onError: (err: any) => {
      addLog(`Seed error: ${err?.message || 'Operation failed'}`);
    }
  });

  const genPlanMut = useMutation({ 
    mutationFn: generatePlan, 
    onSuccess: () => { 
      setActiveStep(2);
      addLog('Initial response plan generated by OR-Tools solver.'); 
      qc.invalidateQueries(); 
    },
    onError: (err: any) => {
      addLog(`Plan generation error: ${err?.message || 'Operation failed'}`);
    }
  });

  const newIncMut = useMutation({ 
    mutationFn: () => addNewIncident(), 
    onSuccess: () => { 
      setActiveStep(3);
      addLog('Severity 5 critical incident injected into system.'); 
      qc.invalidateQueries(); 
    },
    onError: (err: any) => {
      addLog(`Add incident error: ${err?.message || 'Operation failed'}`);
    }
  });

  const resUnavMut = useMutation({ 
    mutationFn: () => makeResourceUnavailable('A2'), 
    onSuccess: () => { 
      setActiveStep(4);
      addLog('Ambulance A2 marked UNAVAILABLE (mechanical failure).'); 
      qc.invalidateQueries(); 
    },
    onError: (err: any) => {
      addLog(`Breakdown error: ${err?.message || 'Operation failed'}`);
    }
  });

  const replanMut = useMutation({ 
    mutationFn: () => replan('simulation_event'), 
    onSuccess: () => { 
      setActiveStep(5);
      addLog('Dynamic replanning executed. Check Command Center for allocations.'); 
      qc.invalidateQueries(); 
    },
    onError: (err: any) => {
      addLog(`Replanning error: ${err?.message || 'Operation failed'}`);
    }
  });

  const resetMut = useMutation({ 
    mutationFn: resetSimulation, 
    onSuccess: () => { 
      setActiveStep(0);
      addLog('Simulation reset to baseline state.'); 
      qc.invalidateQueries(); 
    },
    onError: (err: any) => {
      addLog(`Reset error: ${err?.message || 'Operation failed'}`);
    }
  });

  const isPending = seedMut.isPending || genPlanMut.isPending || newIncMut.isPending || resUnavMut.isPending || replanMut.isPending || resetMut.isPending;

  const standbyCount = resources?.filter(r => r.status === 'AVAILABLE').length || 0;
  const activeIncidents = incidents?.filter(i => i.status === 'ACTIVE') || [];

  return (
    <div className="min-h-[calc(100vh-6rem)] bg-slate-950 p-6 text-slate-100">
      <div className="max-w-5xl mx-auto space-y-6">
        {/* Header */}
        <div className="flex items-center justify-between pb-4 border-b border-slate-800">
          <div>
            <h1 className="text-xl font-bold text-white tracking-tight">Scenario Simulation Controller</h1>
            <p className="text-xs text-slate-400 mt-0.5">
              Simulate dynamic incident escalations, fleet breakdowns, and real-time replanning.
            </p>
          </div>

          <button 
            onClick={() => resetMut.mutate()} 
            disabled={isPending}
            className="flex items-center gap-1.5 px-3 py-1.5 bg-slate-800 hover:bg-slate-700 text-slate-300 rounded-lg text-xs font-medium transition disabled:opacity-50"
          >
            <RotateCcw className="w-3.5 h-3.5" />
            <span>Reset Demo</span>
          </button>
        </div>

        {/* Step-by-Step Flow */}
        <div className="space-y-2">
          <div className="text-xs font-semibold text-slate-400 uppercase tracking-wider">
            Demo Scenario Steps
          </div>

          <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-5 gap-3">
            <button 
              onClick={() => seedMut.mutate()} 
              disabled={isPending}
              className={`p-3.5 rounded-xl border text-left transition ${
                seedMut.isPending ? 'border-blue-500 bg-blue-950/40 ring-1 ring-blue-500/50' :
                activeStep >= 1 
                  ? 'bg-slate-800/80 border-blue-500/50' 
                  : 'bg-slate-900 border-slate-800 hover:border-slate-700'
              }`}
            >
              <div className="flex items-center justify-between mb-2">
                <span className="w-5 h-5 rounded-md bg-slate-800 text-slate-300 text-xs font-semibold flex items-center justify-center">1</span>
                {seedMut.isPending ? <Loader2 className="w-4 h-4 text-blue-400 animate-spin" /> : <Database className="w-4 h-4 text-blue-400" />}
              </div>
              <div className="font-medium text-xs text-white">Seed Data</div>
              <p className="text-[11px] text-slate-400 mt-0.5">3 Incidents + 17 Units</p>
            </button>

            <button 
              onClick={() => genPlanMut.mutate()} 
              disabled={isPending}
              className={`p-3.5 rounded-xl border text-left transition ${
                genPlanMut.isPending ? 'border-amber-500 bg-amber-950/40 ring-1 ring-amber-500/50' :
                activeStep >= 2 
                  ? 'bg-slate-800/80 border-blue-500/50' 
                  : 'bg-slate-900 border-slate-800 hover:border-slate-700'
              }`}
            >
              <div className="flex items-center justify-between mb-2">
                <span className="w-5 h-5 rounded-md bg-slate-800 text-slate-300 text-xs font-semibold flex items-center justify-center">2</span>
                {genPlanMut.isPending ? <Loader2 className="w-4 h-4 text-amber-400 animate-spin" /> : <Zap className="w-4 h-4 text-amber-400" />}
              </div>
              <div className="font-medium text-xs text-white">Generate Plan</div>
              <p className="text-[11px] text-slate-400 mt-0.5">OR-Tools Optimization</p>
            </button>

            <button 
              onClick={() => newIncMut.mutate()} 
              disabled={isPending}
              className={`p-3.5 rounded-xl border text-left transition ${
                newIncMut.isPending ? 'border-red-500 bg-red-950/40 ring-1 ring-red-500/50' :
                activeStep >= 3 
                  ? 'bg-slate-800/80 border-red-500/50' 
                  : 'bg-slate-900 border-slate-800 hover:border-slate-700'
              }`}
            >
              <div className="flex items-center justify-between mb-2">
                <span className="w-5 h-5 rounded-md bg-slate-800 text-slate-300 text-xs font-semibold flex items-center justify-center">3</span>
                {newIncMut.isPending ? <Loader2 className="w-4 h-4 text-red-400 animate-spin" /> : <Plus className="w-4 h-4 text-red-400" />}
              </div>
              <div className="font-medium text-xs text-white">Add S5 Crisis</div>
              <p className="text-[11px] text-slate-400 mt-0.5">Major incident injection</p>
            </button>

            <button 
              onClick={() => resUnavMut.mutate()} 
              disabled={isPending}
              className={`p-3.5 rounded-xl border text-left transition ${
                resUnavMut.isPending ? 'border-amber-500 bg-amber-950/40 ring-1 ring-amber-500/50' :
                activeStep >= 4 
                  ? 'bg-slate-800/80 border-amber-500/50' 
                  : 'bg-slate-900 border-slate-800 hover:border-slate-700'
              }`}
            >
              <div className="flex items-center justify-between mb-2">
                <span className="w-5 h-5 rounded-md bg-slate-800 text-slate-300 text-xs font-semibold flex items-center justify-center">4</span>
                {resUnavMut.isPending ? <Loader2 className="w-4 h-4 text-amber-400 animate-spin" /> : <Ambulance className="w-4 h-4 text-amber-400" />}
              </div>
              <div className="font-medium text-xs text-white">Breakdown A2</div>
              <p className="text-[11px] text-slate-400 mt-0.5">Vehicle unavailable</p>
            </button>

            <button 
              onClick={() => replanMut.mutate()} 
              disabled={isPending}
              className={`p-3.5 rounded-xl border text-left transition ${
                replanMut.isPending ? 'border-purple-500 bg-purple-950/40 ring-1 ring-purple-500/50' :
                activeStep >= 5 
                  ? 'bg-slate-800/80 border-purple-500/50' 
                  : 'bg-slate-900 border-slate-800 hover:border-slate-700'
              }`}
            >
              <div className="flex items-center justify-between mb-2">
                <span className="w-5 h-5 rounded-md bg-slate-800 text-slate-300 text-xs font-semibold flex items-center justify-center">5</span>
                {replanMut.isPending ? <Loader2 className="w-4 h-4 text-purple-400 animate-spin" /> : <RefreshCw className="w-4 h-4 text-purple-400" />}
              </div>
              <div className="font-medium text-xs text-white">Dynamic Replan</div>
              <p className="text-[11px] text-slate-400 mt-0.5">Re-optimize fleet</p>
            </button>
          </div>

          {activeStep >= 2 && (
            <div className="flex items-center justify-between p-3 bg-blue-950/40 border border-blue-800/60 rounded-xl mt-3">
              <div className="text-xs text-blue-200">
                <span className="font-semibold text-blue-400">Response Plan Active:</span> Fleet units have been allocated with real routes and ETAs.
              </div>
              <Link 
                to="/command" 
                className="inline-flex items-center gap-1.5 px-3 py-1.5 bg-blue-600 hover:bg-blue-500 text-white text-xs font-medium rounded-lg transition"
              >
                <span>View Command Center</span>
                <ArrowRight className="w-3.5 h-3.5" />
              </Link>
            </div>
          )}
        </div>

        {/* State Telemetry Split */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div className="bg-slate-900 border border-slate-800 rounded-xl p-4">
            <h3 className="text-xs font-semibold text-slate-300 mb-3">Active Incidents ({activeIncidents.length})</h3>
            <div className="space-y-1.5 max-h-48 overflow-y-auto">
              {activeIncidents.length === 0 ? (
                <p className="text-xs text-slate-500 py-3">No active incidents</p>
              ) : (
                activeIncidents.map(inc => (
                  <div key={inc.id} className="bg-slate-800/40 rounded-lg p-2 flex items-center justify-between text-xs">
                    <span className="text-slate-300 font-medium">#{inc.id} &middot; {inc.type}</span>
                    <SeverityBadge severity={inc.severity} />
                  </div>
                ))
              )}
            </div>
          </div>

          <div className="bg-slate-900 border border-slate-800 rounded-xl p-4">
            <div className="flex items-center justify-between mb-3">
              <h3 className="text-xs font-semibold text-slate-300">Fleet Resources ({resources?.length || 0})</h3>
              <span className="text-xs text-emerald-400">{standbyCount} Available</span>
            </div>
            <div className="space-y-1 max-h-48 overflow-y-auto">
              {resources?.map(r => (
                <div key={r.id} className="bg-slate-800/40 rounded-lg px-2.5 py-1.5 flex items-center justify-between text-xs">
                  <span className="text-slate-300">{r.name}</span>
                  <StatusBadge status={r.status} />
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Event Log */}
        <div className="bg-slate-900 border border-slate-800 rounded-xl p-4 space-y-2">
          <div className="flex items-center justify-between">
            <h3 className="text-xs font-semibold text-slate-300">Simulation Event Log</h3>
            <button 
              onClick={() => setLog([])}
              className="text-[11px] text-slate-500 hover:text-slate-300"
            >
              Clear
            </button>
          </div>

          <div className="bg-slate-950 border border-slate-850 rounded-lg p-3 max-h-36 overflow-y-auto space-y-1 font-mono text-xs text-slate-300">
            {log.map((entry, i) => (
              <p key={i} className="text-slate-400">{entry}</p>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
